
version: '3.8'

services:
  nginx:
    image: mirror.gcr.io/nginx:latest
    volumes:
      - ./auth_service/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - auth_service
    ports:
      - "8000:80"

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JAEGER_HOST=jaeger  # Добавляем Jaeger хост
      - JAEGER_PORT=6831    # Добавляем Jaeger порт
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger: # Указываем зависимость от Jaeger
        condition: service_started

  create_superuser:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python main.py app create-admin

  migrate:
    build:
      context: ./auth_service
      dockerfile: migrate.Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      timeout: 1m
      retries: 5
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.31
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"  # Порт для Thrift UDP
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"    # Интерфейс Jaeger
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

volumes:
  postgres_data:
  redis_data: